version: 2

models:
  - name: box_sales
    description: "Table des ventes de box"
    columns:
      - name: sub_id
        description: "Identifiant unique de souscription"
        tests:
          - unique:
              severity: error