version: 2

models:
  - name: box_sales
    description: "Table des ventes de box"
    tests:
      - unique:
          combination_of_columns:
            - dw_country_code
            - sub_id
          severity: warn
          config:
            store_failures: true