version: 2

models:
  - name: partial_box_paid
    description: "Table des ventes partielles de box"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sub_id
            - dw_country_code
        severity: warn  # Correction d'indentation
        config:
          store_failures: true
          name: "Doublons_partial_box_paid"
