# Nom du projet (doit être en minuscules et sans espaces)
name: 'dwh'
version: '1.0.0'
config-version: 2

# Profil à utiliser pour la connexion aux bases de données
profile: 'default'

# Emplacements des différents fichiers de dbt
model-paths: ["models"]  # Assurez-vous que vos modèles sont dans ce dossier
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Chemin cible pour les fichiers compilés
target-path: "target"  # Dossier pour stocker les fichiers SQL compilés
clean-targets:         # Dossiers supprimés par la commande `dbt clean`
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  dwh:
    accounting:
      +materialized: table
    allocation:
      +materialized: table
    blissim_analytics:
      +materialized: table
    marketing:
      +materialized: table
    ops:
      +materialized: table
    payment:
      +materialized: table
    pnl:
      +materialized: table
    product:
      +materialized: table
    sales:
      +materialized: table
    snippets:
      +materialized: table
    survey:
      +materialized: table
    traffic:
      +materialized: table
    user:
      +materialized: table
