# Nom du projet (doit être en minuscules et sans espaces)
name: 'dwh'
version: '1.0.0'
config-version: 2

# Profil à utiliser pour la connexion aux bases de données
profile: 'default'

# Emplacements des différents fichiers de dbt
model-paths: ["models"]  # Assurez-vous que vos modèles sont dans ce dossier
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Chemin cible pour les fichiers compilés
target-path: "target"  # Dossier pour stocker les fichiers SQL compilés
clean-targets:         # Dossiers supprimés par la commande `dbt clean`
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  dwh:  # Configuration pour tous les modèles dans le dossier dwh
    +schema: dwh_schema
    dwh.accounting:  # Sous-dossier models/dwh/accounting
      +materialized: table
    dwh.allocation:  # Sous-dossier models/dwh/allocation
      +materialized: table
    dwh.blissim_analytics:  # Sous-dossier models/dwh/blissim_analytics
      +materialized: table
    dwh.marketing:  # Sous-dossier models/dwh/marketing
      +materialized: table
    dwh.ops:  # Sous-dossier models/dwh/ops
      +materialized: table
    dwh.payment:  # Sous-dossier models/dwh/payment
      +materialized: table
    dwh.product:  # Sous-dossier models/dwh/product
      +materialized: table
    dwh.sales:  # Sous-dossier models/dwh/sales
      +materialized: table
    dwh.snippets:  # Sous-dossier models/dwh/snippets
      +materialized: table
    dwh.inter:  # Sous-dossier models/dwh/inter
      +materialized: table

  customer:  # Configuration pour tous les modèles dans le dossier customer
    +schema: customer_schema
    customer.segmentation:  # Sous-dossier models/customer/segmentation
      +materialized: table
