name: 'data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

models:
 +materialized: table # Configuration globale
 
 customer:  # Models du domaine customer
   +schema: customer
   +enabled: true
   
 dwh:  # Models du domaine dwh
   +schema: dwh 
   +enabled: false