# Nom du projet (doit être en minuscules et sans espaces)
name: 'warehouse'
version: '1.0.0'
config-version: 2

# Profil à utiliser pour la connexion aux bases de données
profile: 'default'

# Emplacements des différents fichiers de dbt
model-paths: ["models"]  # Assurez-vous que vos modèles sont dans ce dossier
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Chemin cible pour les fichiers compilés
target-path: "target"  # Dossier pour stocker les fichiers SQL compilés
clean-targets:         # Dossiers supprimés par la commande `dbt clean`
  - "target"
  - "dbt_packages"

# Variables globales
vars:
  survey_countries:
    - code: 'FR'
      dataset: 'bdd_prod_fr'
    - code: 'DE'
      dataset: 'prod_de'
    - code: 'ES'
      dataset: 'bdd_prod_es'
    - code: 'IT'
      dataset: 'bdd_prod_it'


# Configuration des modèles
models:
  warehouse:
    +store_failures: true
    dwh:
      +query_tag: "no_cache"
      +materialized: table
      region: europe-west1
      +schema: dwh_schema
      accounting:
      allocation:
      blissim_analytics:
      marketing:
      ops:
      payment:
      pnl:
      product: 
      sales:
        +persist_docs:
          relation: true
          columns: true
      snippets:
      inter:
        +schema: inter
        +materialized: table
        table:
          +materialized: table
        materialized_views:
          refresh_4h:
            +materialized: materialized_view
            enable_refresh: true
            max_staleness: 'INTERVAL "0:30:0" HOUR TO SECOND'
            refresh_interval_minutes: 360
        merge:
          +materialized: incremental
          +on_schema_change: sync_all_columns
          +unique_key: ['id', 'dw_country_code']

        
    schedule:
      +materialized: table
      daily:
        5am:
          teamdata:
          normalised:
            +database: normalised-417010
      hourly:
        30mn:
          teamdata:
        1H:
          normalised:
            +database: normalised-417010
        4H:
          normalised:
            +database: normalised-417010
      custom:
        history_table:
          normalised:
            +database: normalised-417010
          teamdata:
            +materialized: table
seeds:
  warehouse:               
    +schema: referentiel   # dataset BigQuery cible, tu peux le renommer si tu préfères `referentiel` ou `marketing_ref` etc.
    +quote_columns: false
    +delimiter: ";"
    +encoding: UTF-8

    referentiel:
      insee_iris_csp:
        +column_types:
          IRIS: string
          COM: string
          TYP_IRIS: string
          LAB_IRIS: string
          C20_ACT1564: float64
          C20_ACT1564_CS1: float64
          C20_ACT1564_CS2: float64
          C20_ACT1564_CS3: float64
          C20_ACT1564_CS4: float64
          C20_ACT1564_CS5: float64
          C20_ACT1564_CS6: float64


                   
