version: 2

models:
  - name: '*'  # Cible tous les modèles
    columns:
      - name: id
        tests:
          - unique
      
      - name: dw_country_code
        tests:
          - unique

    # Pour tester la combinaison des colonnes, on peut utiliser un test SQL personnalisé
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - id
            - dw_country_code