version: 2

models:
  - name: customers
    description: "Table des customers par pays et notion de statut de client et profil beauté"
    columns:
      - name: box_sub_status
        description: "statut de la box (LIVE, CHURN, NEVERSUB)"
      - name: dw_country_code
        description: "Code pays (FR, DE, etc.)"
