version: 2

models:
  - name: partial_box_paid
    description: "Table des ventes partielles de box"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - sub_id
              - dw_country_code
          config:
            severity: warn
            store_failures: true
            name: "Doublons partial_box_paid"
